name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Material Design breakpoints for responsive layouts
  # https://pub.dev/packages/adaptive_breakpoints
  adaptive_breakpoints: ^0.1.6

  # Material Design responsive components for grid layouts
  # https://pub.dev/packages/adaptive_components
  adaptive_components: ^0.0.9

  # Material Design responsive navigation for NavigationRail vs BottomNavigationBar
  # https://pub.dev/packages/adaptive_navigation
  adaptive_navigation: ^0.0.9

  # Pre-canned animations for common effects
  # https://pub.dev/packages/animations
  animations: ^2.0.8

  # Utility functions and classes for collections e.g. shuffle, search, sort, zip etc.
  # https://pub.dev/packages/collection
  collection: ^1.18.0

  # Flutter plugin to change size of desktop window
  # https://pub.dev/packages/desktop_window
  desktop_window: ^0.4.0

  # Create Material color schemes based off the system's theme
  # https://pub.dev/packages/dynamic_color
  dynamic_color: ^1.6.8

  # Alternate state management library vs provider
  # https://pub.dev/packages/dynamic_color
  flutter_bloc: ^8.1.3

  # Model code generation library
  freezed_annotation: ^2.4.1

  # Algorithms and utilities for the Material Design 3 color system
  # https://pub.dev/packages/material_color_utilities
  material_color_utilities: any

  # Replacement for dart.io.Platform that works on all platforms including Web
  universal_platform: ^1.0.0+1

  # Flutter plugin to launch a URL on all platforms
  url_launcher: ^6.2.1

  # Simple URL routing between screens
  go_router: ^12.1.1

  # Simple set of words and functions for mocking out app data
  english_words: ^4.0.0

  # Google fonts like Roboto, Noto Sans etc.
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
